install:
  - gem install package_cloud fpm

rvm:
  - 1.9.2

env:
  - PUPPET_VERSION=3.7.3

script:
  - curl -s https://raw.githubusercontent.com/visibilityspots/jenkins-scripts/master/puppet/package-puppet-module.sh | bash -s pakiti development
  - package_cloud push visibilityspots/puppet-modules/el/6 *.rpm

notifications:
  email:
    - travis@visibilityspots.com
